pipeline:
  name: aerospike-client-c
  identifier: aerospikeclientc
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: aerospike-client-c
        build: <+input>
  stages:
    - stage:
        name: Aerospike C Client Tests
        identifier: Aerospike_C_Client_Tests
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Setup Aerospike Database
                  identifier: Setup_Aerospike_Database
                  spec:
                    shell: Sh
                    command: |-
                      ./install_libev
                      make EVENT_LIB=libev
                      make EVENT_LIB=libev test
                      make clean
        variables:
          - name: LD_LIBRARY_PATH
            type: String
            description: ""
            value: /usr/local/lib
